### ISSUE TITLE
Undefined behavior triggered in C code

### ISSUE THREAD

**Issue by kmicklas** [DataDog/zstd#113]
### What version of Go are you using (`go version`)?

```
go version go1.17.8 linux/amd64
```

### What operating system and processor architecture are you using (`go env`)?

Ubuntu 20.04

### What did you do?

I don't currently have a simple reproduction example for this, but it seems like all of our tests using this library will crash if you enable UBSAN (`-fsanitize=undefined`) with zig cc / clang as the C toolchain.

### What did you expect to see?

Code using this library executes successfully with UBSAN.

### What did you see instead?

Here is an example snippet which may narrow down the bug:

```
runtime.cgocall(0x27d7850, 0xc00086b700)
	GOROOT/src/runtime/cgocall.go:156 +0x5c fp=0xc00086b6d8 sp=0xc00086b6a0 pc=0x16abbfc
github.com/DataDog/zstd._Cfunc_ZSTD_compressBegin(0x7f00fc000c50, 0x5)
	_cgo_gotypes.go:178 +0x4d fp=0xc00086b700 sp=0xc00086b6d8 pc=0x278b36d
github.com/DataDog/zstd.NewWriterLevelDict.func1(0x7f00fc000c50, 0x5)
	__main__/external/com_github_datadog_zstd/zstd_stream.go:68 +0x4f fp=0xc00086b730 sp=0xc00086b700 pc=0x278be6f
github.com/DataDog/zstd.NewWriterLevelDict({0x958ae0, 0xc000994330}, 0x5, {0x0, 0x0, 0x0})
	__main__/external/com_github_datadog_zstd/zstd_stream.go:68 +0xc5 fp=0xc00086b788 sp=0xc00086b730 pc=0x278bb65
github.com/DataDog/zstd.NewWriter(...)
	__main__/external/com_github_datadog_zstd/zstd_stream.go:46
```

I think this should be pretty easy to reproduce if you enable UBSAN, but if there is any trouble I can try to provide more debugging info.

**Comment by bsergean** [comment]
Do the UBSAN problem also exists in the zstd library, or are they unique to the datadog / zstd binding ?

**Comment by Viq111** [comment]
I'm going to close this one it's unclear whether the report lies in `facebook/zstd` or `DataDog/zstd`, feel free to reopen/create a new issue if this relates to the Go zstd wrapper
