### ISSUE TITLE
Not Support Apple M1

### ISSUE THREAD

**Issue by zhangliquan01** [DataDog/zstd#121]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.18.3 darwin/arm64

### What operating system and processor architecture are you using (`go env`)?

GO111MODULE="on"
GOARCH="arm64"
GOBIN=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOOS="darwin"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_arm64"
GOVCS="*:all"
GOVERSION="go1.18.3"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="0"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/4g/3my1x_q956546f1thn9w77hh0000gq/T/go-build1255549476=/tmp/go-build -gno-record-gcc-switches -fno-common"

### What did you do?

If possible, provide a recipe for reproducing the error.
If you have issues building, please parse the output of `go build -x`

WORK=/var/folders/4g/3my1x_q956546f1thn9w77hh0000gq/T/go-build2505517206
package command-line-arguments
        imports git.garena.com/shopee/deep/algo-search/internal/app
        imports git.garena.com/shopee/deep/algo-search-common/fp
        imports git.garena.com/shopee/deep/paidads-superkia/client/fetch
        imports git.garena.com/shopee/deep/paidads-superkia/kia
        imports git.garena.com/shopee/deep/paidads-superkia/internal/feature
        imports git.garena.com/shopee/deep/paidads-superkia/internal/compress
        imports github.com/DataDog/zstd: build constraints exclude all Go files in /Users/liquan.zhang/go/src/git.garena.com/shopee/deep/algo-search/vendor/github.com/DataDog/zstd

**Comment by Viq111** [comment]
Hi @zhangliquan01, thanks for posting an issue.
From your `go env` paste, it seems like cgo is disabled (`CGO_ENABLED="0"`) so this is why you cannot compile it. It seems like you or your company set it to False ?
Go has an [open issue](https://github.com/golang/go/issues/24068) to make the error more explicit.

If after enabling Cgo and making sure your C toolchain works, you are still having issues, let us know

**Comment by zhangliquan01** [comment]
it works, thank you very much
