### ISSUE TITLE
Update to Zstandard v1.5.5

### ISSUE THREAD

**Issue by twalwyn** [DataDog/zstd#124]
FYI, in case this hadn't crossed anyones radar. It might be prudent to vendor v1.5.5.

From https://github.com/facebook/zstd/releases/tag/v1.5.5:

> This is a quick fix release. The primary focus is to correct a rare corruption bug in high compression mode, detected by @danlark1. The probability to generate such a scenario by random chance is extremely low. It evaded months of continuous fuzzer tests, due to the nb and complexity of simultaneous conditions required to trigger it. Nevertheless, @danlark1 from Google shepherds such a humongous amount of data that he managed to detect a reproduction case (corruptions are detected thanks to the checksum), making it possible for @terrelln to investigate and fix the bug. Thanks !

**Comment by Viq111** [comment]
Thanks! Merged to [1.x](https://github.com/DataDog/zstd/tree/1.x) and cutting a pre-release
