### ISSUE TITLE
panic: "unexpected signal during runtime execution"

### ISSUE THREAD

**Issue by mappu** [DataDog/zstd#13]
Hi, thanks so much for releasing this binding. 

I'm trying to track down a strange panic when this library is combined with some others. It's entirely possible that it has nothing to do with `DataDog/zstd`, but i can't reduce my test case any further.

Would you be able to comment on https://github.com/golang/go/issues/19468#issuecomment-285259553 ?

Is there any chance the C code in this library is writing to memory it doesn't own?

**Comment by Viq111** [comment]
Hi @mappu, I'm following the original issue at https://github.com/golang/go/issues/19468#issuecomment-285259553 and not sure I can add more information.

You are using the `Compress` method in your example which is really simple and 20 lines of code ([source](https://github.com/DataDog/zstd/blob/1.x/zstd.go#L89-L116)) so I don't think there is something from the bindings side.

Looking at the C code, there is an object allocation "outside" the go code for the context ([source](https://github.com/DataDog/zstd/blob/1.x/zstd_compress.c#L2750-L2754)), but this is created and freed during the C call so it shouldn't make the go runtime panic.

**Comment by mappu** [comment]
In the end, this issue was resolved by https://github.com/Microsoft/go-winio/pull/48 in the other repository. Closing!
