### ISSUE TITLE
build Error

### ISSUE THREAD

**Issue by ywolf** [DataDog/zstd#14]
Win7 build cross-linux64
go build github.com/DataDog/zstd: no buildable Go source files in E:\go\test\src\github.com\DataDog\zstd

**Comment by Viq111** [comment]
Hey @ywolf can you provide a little bit more debug infos (go version, `go build -x`) ?

Also this zstd binding use cgo, so you'll need a cross-compiling C toolchain to be able to compile to linux from windows (never cross-compiled cgo myself before)

**Comment by Viq111** [comment]
closing, but feel free to reopen if you have more information
