### ISSUE TITLE
Zstandard v1.5.6 is available

### ISSUE THREAD

**Issue by ribasushi** [DataDog/zstd#140]
Please consider pulling [the latest upstream](https://github.com/facebook/zstd/releases/tag/v1.5.6). Specifically that release contains some interesting fixes for issues lile:
- https://github.com/facebook/zstd/issues/3793
- https://github.com/facebook/zstd/issues/3014

**Comment by Viq111** [comment]
Thanks for the ping! Draft PR here: https://github.com/DataDog/zstd/pull/143
I will run some additional benchmarks before marking it as ready to review

**Comment by Viq111** [comment]
https://github.com/DataDog/zstd/releases/tag/v1.5.6
