### ISSUE TITLE
Writer performs poorly on small writes

### ISSUE THREAD

**Issue by lunixbochs** [DataDog/zstd#16]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.8.1

### What operating system and processor architecture are you using (`go env`)?
darwin amd64

### What did you do?
I used zstd.Writer() to compress very small chunks (a few bytes) at a time.

This is a reproduction case:
```
package main

import (
	"github.com/datadog/zstd"
	"os"
)

func main() {
	input, _ := os.Open("input")
	output, _ := os.Create("output")
	z := zstd.NewWriter(output)
	for {
		var tmp [1]byte
		_, err := input.Read(tmp[:])
		if err != nil {
			break
		}
		z.Write(tmp[:])
	}
	z.Close()
}
```

### What did you expect to see?
Compression.

### What did you see instead?
ZSTD is very slow (several times worse than any variant of compressing or not compressing) and balloons the file size (several times larger than the input) when used in this manner. I get files that are several times larger and take several times longer to compress.

I don't think it makes sense to provide an io.Writer without buffering into a minimum chunk size, as done by snappy with their BufferedWriter:

https://github.com/golang/snappy/blob/master/encode.go#L126

**Comment by Viq111** [comment]
Hey @lunixbochs, thanks for reporting! To get a sense of the speed you are expecting, would it be possible to provide the input byte size and how much speed you see / expect from zstd and from snappy or other compression lib ?

The main difference here is that the snappy library you posted is pure Go whereas this zstd lib is using CGo. When creating a `io.Writer`, we create a C context for zstd and then do at least 2 CGo calls so it's bound to be way slower. When doing small inputs, I'd highly recommend using the `zstd.Compress` / `zstd.Decompress` methods as this will make only a single CGo call and should be significantly faster

_Edit:_
Sorry I didn't read the issue in full, I don't think it really makes sense to reimplement a buffered writer for every compression lib, I think it would make more sense to have an intermediate reader/writer (ala https://golang.org/pkg/io/#TeeReader or https://golang.org/pkg/io/#LimitedReader) to be able to do that for any lib.

**Comment by lunixbochs** [comment]
My input is >20MB (which is on the very small end for me), but I feed it into the writer a few bytes at a time (as it's created. I'm serializing a very large stream of very small objects to disk for tracing a program's state). Based on a quick glance at the output, looks like streaming zstd like this adds some kind of frame every time you compress.

**Comment by lunixbochs** [comment]
Hmm, `bufio` might be able to do this with [NewWriterSize()](https://golang.org/pkg/bufio/#NewWriterSize), but I already tried a bufio and didn't get any better results.

You could probably wrap your default writer with bufio as basically a net gain (and would need to expose as WriteCloser / document Close requirement), but I think I already tried wrapping bufio around datadog/zstd and it didn't help.

Edit: wrapping bufio does appear to fix the problem, so I think datadog/zstd should either wrap with bufio by default, or expose a BufferedWriter that is just `bufio.NewWriter(zstd.Writer(w))` with `func Close() { bufio.Flush(); z.Close() }` and document it as practically necessary for small writes. As is, small writes to the writer will be expanded to larger than they started.

**Comment by Viq111** [comment]
From

```go
package main

import (
	"bytes"
	"github.com/datadog/zstd"
	"github.com/dustin/randbo"
	"io"
	"io/ioutil"
	"testing"
)

type BufferedWriter struct {
	BufferSize       int
	buffer           bytes.Buffer
	underlyingOutput io.WriteCloser
}

func NewBufferedWriter(output io.WriteCloser, bufferSize int) *BufferedWriter {
	return &BufferedWriter{
		BufferSize:       bufferSize,
		underlyingOutput: output,
	}
}

func (b *BufferedWriter) Write(p []byte) (n int, err error) {
	n, err = b.buffer.Write(p)
	if b.buffer.Len() > b.BufferSize { // Flush
		_, err = b.underlyingOutput.Write(b.buffer.Bytes())
		b.buffer.Reset()
	}
	return n, err
}

func (b *BufferedWriter) Close() error {
	if b.buffer.Len() > 0 {
		_, err := b.underlyingOutput.Write(b.buffer.Bytes())
		return err
	}
	return nil
}

func BenchmarkNonBufferedCompression(b *testing.B) {
	r := randbo.New()
	input := make([]byte, b.N+1)
	r.Read(input)
	b.SetBytes(1)
	z := zstd.NewWriter(ioutil.Discard)
	defer z.Close()
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		z.Write(input[i : i+1])
	}
}

func BenchmarkBufferedCompression(b *testing.B) {
	r := randbo.New()
	input := make([]byte, b.N+1)
	r.Read(input)
	b.SetBytes(1)
	z := zstd.NewWriter(ioutil.Discard)
	defer z.Close()
	buf := NewBufferedWriter(z, 1024*1024)
	defer buf.Close()
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		buf.Write(input[i : i+1])
	}
}
```

I get (`go version go1.8.1 darwin/amd64`):

```go
ᐅ go test buffered_test.go -bench .
BenchmarkNonBufferedCompression-4   	 5000000	       331 ns/op	   3.02 MB/s
BenchmarkBufferedCompression-4      	100000000	        20.9 ns/op	  47.94 MB/s
```

Would that be in the range of what you'd expect from other compressions ?

**Comment by lunixbochs** [comment]
It beats stdlib compressors (lzw and zlib) by a fair bit now, though it's interesting to note buffering compress/zlib to 1MB also speeds it up quite a bit.

Using bufio.Writer directly instead of indirecting the Write has a good speedup here (50%), which puts you at around 3x buffered zlib and 2x buffered lzw, which is a huge win over the std library with default settings in my book.

```
NonBuffered     5000000    325 ns/op    3.08 MB/s
Buffered      100000000    20.9 ns/op   47.78 MB/s
Bufio         100000000    14.8 ns/op   67.66 MB/s
Zlib           20000000    66.4 ns/op   15.05 MB/s
BufioZlib      50000000    36.4 ns/op   27.49 MB/s
Snappy        200000000    8.62 ns/op   116.05 MB/s
BufioSnappy   100000000    10.7 ns/op   93.15 MB/s
BufioLzw       50000000    32.7 ns/op   30.61 MB/s
```

https://gist.github.com/lunixbochs/abd22a84df8ecb6016d393474a2bdb38

I set the level to 1 instead of 5 (which is weird, as zstd says the default level should be 1), and speed shot up even further to around 80MB/s (4x stdlib best).
I then tweaked the writes to be closer to my workload (~4B instead of 1B), and got these speeds:

```
NonBuffered    20000000   96.7 ns/op   10.34 MB/s
Buffered      200000000   8.20 ns/op   121.88 MB/s
Bufio         200000000   6.67 ns/op   150.01 MB/s
FastBufio     500000000   3.33 ns/op   300.74 MB/s
Zlib           50000000   36.0 ns/op   27.75 MB/s
BufioZlib      50000000   28.0 ns/op   35.66 MB/s
Snappy       1000000000   2.24 ns/op   446.86 MB/s
BufioSnappy  1000000000   2.84 ns/op   352.05 MB/s
BufioLzw       50000000   24.4 ns/op   40.97 MB/s
```

https://gist.github.com/lunixbochs/7fb386c469f9c6a8c38739777dd2b681

This puts you much closer to snappy, and far ahead of the entire stdlib. (However, whatever snappy is doing to buffer still seems better than this. zstd is almost as fast as snappy/bufio at 4B writes, but 150MB/s slower than snappy's buffer)

Edit: I don't actually know how the MB/s at the end is calculated, so skipping benchmark executions could throw it off?

**Comment by Viq111** [comment]
Nice benchmarks! Yes bufio implementation should be definitly way better than my quick & dirty buffer implementation. Zstd is meant to compete in the same field as zlib in term of compression ratio and speed, not in the snappy league (which trades off ratio for speed; lz4 could be a contender there, by the same author as zstd).

For `MB/s` this is computed by setting the `b.SetBytes(x)` where x is how many bytes you handle in a `i := 0; i < b.N; i++` loop (so should be `1` for first test and `4` for second one) if that's the question you are asking ?
`DefaultCompression` was set here: https://github.com/DataDog/zstd/blob/1.x/zstd.go#L58 to be in the same range in term of ratio to what zlib level 4 (zlib default) provided

**Comment by jcftang** [comment]
I'm not sure if you want to have the bindings to do the buffering for you in a transparent way, maybe a few new BufferedWriter() methods should be created. As a consumer of the library I would prefer to know whats going on with the write so I don't loose data because I didn't do what was expected.

**Comment by develar** [comment]
BTW, in my experiments the best buffer size is 32MB. And minimal 1MB (as it seems ZSTD CLI uses). https://github.com/develar/zstd-archiver/blob/master/tar/compress.go#L34

It is quite unexpected that by default Stream API produces not expected result (compression ratio not good, in my case 42MB (32MB buffer) vs 56MB (no buffer)). It is quite logical, but still not expected for non-experienced user.

Probably it is just documentation issue.

**Comment by valyala** [comment]
@lunixbochs  and @develar , try [gozstd.Writer](https://godoc.org/github.com/valyala/gozstd#Writer). It should work without additional buffering. Here are benchmark results for 1-byte, 10-byte and 100-byte writes with various randomness for input data. Randomness is in the range from 1 (all zeroes) to 256 (100% random data, i.e. uncompressible data):

```
$ go test -run=111 -bench='Writer/blockSize_10{0,2}$' github.com/valyala/gozstd
goos: linux
goarch: amd64
pkg: github.com/valyala/gozstd
BenchmarkWriter/blockSize_1/randomness_1-4         	 1000000	      1365 ns/op	  73.23 MB/s	       0 B/op	       0 allocs/op
BenchmarkWriter/blockSize_1/randomness_10-4        	 1000000	      1620 ns/op	  61.72 MB/s	       0 B/op	       0 allocs/op
BenchmarkWriter/blockSize_1/randomness_20-4        	 1000000	      1758 ns/op	  56.85 MB/s	       0 B/op	       0 allocs/op
BenchmarkWriter/blockSize_1/randomness_50-4        	 1000000	      2033 ns/op	  49.18 MB/s	       0 B/op	       0 allocs/op
BenchmarkWriter/blockSize_1/randomness_256-4       	  500000	      3331 ns/op	  30.02 MB/s	       0 B/op	       0 allocs/op
BenchmarkWriter/blockSize_10/randomness_1-4        	 1000000	      1586 ns/op	 630.46 MB/s	       0 B/op	       0 allocs/op
BenchmarkWriter/blockSize_10/randomness_10-4       	  300000	      5195 ns/op	 192.47 MB/s	       0 B/op	       0 allocs/op
BenchmarkWriter/blockSize_10/randomness_20-4       	  300000	      3877 ns/op	 257.87 MB/s	       0 B/op	       0 allocs/op
BenchmarkWriter/blockSize_10/randomness_50-4       	  300000	      4356 ns/op	 229.54 MB/s	       0 B/op	       0 allocs/op
BenchmarkWriter/blockSize_10/randomness_256-4      	  200000	      8872 ns/op	 112.71 MB/s	       0 B/op	       0 allocs/op
BenchmarkWriter/blockSize_100/randomness_1-4       	  500000	      2207 ns/op	4529.97 MB/s	       0 B/op	       0 allocs/op
BenchmarkWriter/blockSize_100/randomness_10-4      	   30000	     44685 ns/op	 223.79 MB/s	       1 B/op	       0 allocs/op
BenchmarkWriter/blockSize_100/randomness_20-4      	  100000	     12839 ns/op	 778.83 MB/s	       0 B/op	       0 allocs/op
BenchmarkWriter/blockSize_100/randomness_50-4      	  100000	     13422 ns/op	 745.01 MB/s	       0 B/op	       0 allocs/op
BenchmarkWriter/blockSize_100/randomness_256-4     	  200000	      7875 ns/op	1269.68 MB/s	       0 B/op	       0 allocs/op
PASS
ok  	github.com/valyala/gozstd	23.666s
```
