### ISSUE TITLE
How to enable ZSTD_LEGACY_SUPPORT?

### ISSUE THREAD

**Issue by davies** [DataDog/zstd#19]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go version go1.9.1 darwin/amd64

### What did you do?

If possible, provide a recipe for reproducing the error.
If you have issues building, please parse the output of `go build -x`

I'd like to upgrade the zstd we used from 0.7 to 1.3 with legacy support, what's the recommended way to do that?

### What did you expect to see?

zstd 1.3 could decompress data which is compressed with zstd 0.7

### What did you see instead?

It failed with "Unknown frame descriptor"

**Comment by Viq111** [comment]
Hey @davies, I've never done this myself before. What I usually do in that case is define zstd 0.7 (0.6 in our case) as one type of compression and zstd 1.x as another type and do the transition in-app.

However you should be able to do what you want by setting `ZSTD_LEGACY_SUPPORT` to 7: https://github.com/DataDog/zstd/blob/1.x/zstd_legacy.h#L47

You can set it up in [zstd.go](https://github.com/DataDog/zstd/blob/1.x/zstd.go#L4) for example and rebuild with that.

**Comment by davies** [comment]
I have not figured a way without forking this library, end up change the default ZSTD_LEGACY_SUPPORT to 1 in zstd_decompress.c (it's weird that 7 does not work).

In order to link both 0.7 and 1.x into my app, I have to rename lots of symbols in 0.7 from ZSTD_XXX to ZSTD0_XXX, see https://github.com/davies/zstd/tree/v0.7
