### ISSUE TITLE
Could you add an example PAYLOAD value for running tests to README?

### ISSUE THREAD

**Issue by hnakamur** [DataDog/zstd#21]
First of all, thanks for a nice library!

I ran `go test -v` and got the output `zstd_test.go:117: PAYLOAD env was not set`.
However I don't know what value to set to `PAYLOAD` environment variable.

Could you add an explanation to README?
Thanks!

**Comment by Viq111** [comment]
Hi @hnakamur, thanks for your suggestion! I've added an additional comment on https://github.com/DataDog/zstd/commit/066032d653bf59444a83a1c54baeba3a88661410

Basically, by setting the `PAYLOAD` environment variable, you can both test compression / decompression and benchmark against a specific use case. If the variable is not set, it just skips this part (https://github.com/DataDog/zstd/blob/1.x/zstd_test.go#L117)

Hope this helps

**Comment by hnakamur** [comment]
Thanks!
