### ISSUE TITLE
Empty slices cannot be compressed

### ISSUE THREAD

**Issue by bobrik** [DataDog/zstd#41]
### What did you do?

Tried to compress empty slice.

### What did you expect to see?

Empty slice is compressed consistently with `zstd`:

```
$ touch empty

$ zstd empty
empty                :1300.00%   (     0 =>     13 bytes, empty.zst)

$ ls -la empty empty.zst
-rw-r--r--  1 bobrik  staff   0 Sep 30 17:09 empty
-rw-r--r--  1 bobrik  staff  13 Sep 30 17:09 empty.zst

$ cat empty.zst | hexdump -C
00000000  28 b5 2f fd 24 00 01 00  00 99 e9 d8 51           |(./.$.......Q|
0000000d
```

### What did you see instead?

Error `ErrEmptySlice ` (`Bytes slice is empty`) is generated: 611468670913612c338acfa1c1fc852d01f26483.

cc @Viq111

**Comment by Viq111** [comment]
Hi @bobrik,

Thanks for reporting!
Indeed it looks like here this behavior is not desired as we can easily avoid return `EmptySlice`. There is also a difference of behavior between the streaming and non-streaming version.

I fixed it in https://github.com/DataDog/zstd/pull/42 if you want to test it.
For zstd 1.3.4, the compressed message of the empty slice is `0x28b52ffd0050010000`
