### ISSUE TITLE
Bump version

### ISSUE THREAD

**Issue by ctrochalakis** [DataDog/zstd#48]
Hello,

Would you consider cutting a new version that includes all fixes residing in master (empty slice error, empty payload, etc)?

I am packaging `Datadog/zstd` in Debian (https://tracker.debian.org/pkg/golang-github-datadog-zstd) as part of https://github.com/Shopify/sarama dependencies and having a new version instead of backporting patches would be helpful.

Thank you,
Chris

**Comment by Viq111** [comment]
Hi @ctrochalakis, yes sure we can release a bug fix release (we usually keep the major / minor version in sync with the C zstd version we use).
I think we will also want to tackle https://github.com/DataDog/zstd/issues/22 before cutting the next release but in the mean time, the current changes on master are good to go

**Comment by Viq111** [comment]
https://github.com/DataDog/zstd/releases/tag/v1.3.5
