### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by betterz1** [DataDog/zstd#51]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

1.10.1
### What operating system and processor architecture are you using (`go env`)?

centeros 7.5
### What did you do?

If possible, provide a recipe for reproducing the error.
If you have issues building, please parse the output of `go build -x`

### What did you see instead?
when i run go install
DataDog/zstd exec: "gcc": executable file not found in $PATH

**Comment by Viq111** [comment]
Hi @betterz1 !
This project uses [cgo](https://golang.org/cmd/cgo/) so you'll need a C compiler toolchain to build it.

It looks like you are using centos so you can get gcc directly with yum:
```
yum update
yum install gcc
```

**Comment by betterz1** [comment]
i use docker. and from golang:1.10.3  how i use gcc in dockerfile. apk add gcc?




On 01/22/2019 22:47, Vianney Tran wrote:

Hi @betterz1 !
This project uses cgo so you'll need a C compiler toolchain to build it.

It looks like you are using centos so you can get gcc directly with yum:

yum update
yum install gcc

**Comment by Viq111** [comment]
Can you post the full base image dockerfile you are using ?
Looking at the [official Go image](https://hub.docker.com/_/golang?tab=description),  it already installs  gcc for cgo:
https://github.com/docker-library/golang/blob/master/1.10/stretch/Dockerfile#L3-L10

If you are using alpine as base image, randomly looking online it seems you'll need
```
apk add --update go git build-base
```
([Source](https://github.com/aioTV/logspout/pull/2/files))
