### ISSUE TITLE
Compilation finished with exit code 2

### ISSUE THREAD

**Issue by Sufir** [DataDog/zstd#52]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.12 windows/amd64

And _gcc (i686-posix-dwarf-rev2, Built by MinGW-W64 project) 4.9.1_

### What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Go\bin;C:\Go
set GOPROXY=
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=d:\Temp\go-build450666390=/tmp/go-build -gno-record-gcc-switches

### What did you do?

`go build`

### What did you see instead?
# github.com/DataDog/zstd
cc1.exe: sorry, unimplemented: 64-bit mode not compiled in
Compilation finished with exit code 2

**Comment by Viq111** [comment]
Hi @Sufir ! It looks like you are using Go 64bits but you don't have the gcc tooling for 64bits installed.

Looks like this issue might help you: https://github.com/golang/go/issues/3441
Especially this part:
> Thanks, installing mingw-w64 helped.

Let me know if this helps!

**Comment by Sufir** [comment]
@Viq111 yes you right, it's all gcc. I have gcc tooling for 64bits installed, but my version was 4.9. All works after update to 8.1
