### ISSUE TITLE
How to write to an existing zstd file using io.writer?

### ISSUE THREAD

**Issue by zplzpl** [DataDog/zstd#65]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

1.12.6

### What operating system and processor architecture are you using (`go env`)?

set GOARCH=amd64
set GOBIN=D:\goproject\bin
set GOCACHE=C:\Users\Administrator\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=D:\goproject
set GOPROXY=
set GORACE=
set GOROOT=D:\go\1.12.6
set GOTMPDIR=
set GOTOOLDIR=D:\go\1.12.6\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config

### What did you do?

write to an existing zstd file using io.writer

filename := "./test.zstd"
file, err := os.OpenFile(filename, os.O_APPEND|os.O_WRONLY, 0644)
_ = err
w := zstd.NewWriter(file)
w.Write([]byte("aaaaa"))

### What did you expect to see?

Zstd can continue to compress the bytes written without affecting the decompression

### What did you see instead?

When I use zstd.NewReader and ioutil.ReadAll, I get an error: failed to decompress: Corrupted block detected

**Comment by Viq111** [comment]
Hi @zplzpl

There are some internal buffers usually on `io.Writer` and files so you need to properly close the objects to make sure the full data is written:

```go
func panicOnError(err error) {
  if err != nil {
    panic(err)
  }
}

func main() {
  filename := "./test.zstd"
  file, err := os.OpenFile(filename, os.O_APPEND|os.O_WRONLY, 0644)
  panicOnError(err)
  defer file.Close()

  w := zstd.NewWriter(file)
  defer w.Close()
  _, err = w.Write([]byte("aaaaa"))
  panicOnError(err)
}
```

Hope this helps!

**Comment by zplzpl** [comment]
Oh, yes, I didn't do the correct closing operation.

I did what you said and it works.

But I have a problem, if the process crashes and exits, there is no correct close operation. Then there will be problems with continuing to write.

Is there any way to judge this zstd file, whether it was normally closed before?

If not closed properly, then create a new zstd file write.

**Comment by Viq111** [comment]
Ah that makes sense. Hmmm, unfortunately usually those use cases are not directly handled by compression algorithm, they are usually implemented either at the file format layer (For examples, usually all databases have some sort of repair mechanism, see levelDB for example: https://godoc.org/github.com/syndtr/goleveldb/leveldb#Recover)
Or you could implement it with control codes and/or repair indexes (examples: CRCs: https://en.wikipedia.org/wiki/Error_detection_and_correction or https://en.wikipedia.org/wiki/Error_correction_code)

With that being said, zstd does implement an optional checksum control that is not surfaced yet with this library: https://github.com/DataDog/zstd/issues/43. PR are welcomed if you want to implement it!

**Comment by zplzpl** [comment]
thank you
