### ISSUE TITLE
zstd 1.4.4

### ISSUE THREAD

**Issue by limbo127** [DataDog/zstd#72]
Hello, 
can you update to zstd 1.4.4 library ?
regards, 
Nicolas.

**Comment by Viq111** [comment]
Hi @limbo127 !

The upstream zstd was updated by @dbenamydd via PR https://github.com/DataDog/zstd/pull/73

A pre-release has been released at https://github.com/DataDog/zstd/releases/tag/v1.4.4, it will be promoted to final release in a week if there are no bug report!

If you'd like to contribute, PRs are always welcomed as well 🙂
