### ISSUE TITLE
failed to decompress: Unknown frame descriptor If padding is attached after compression

### ISSUE THREAD

**Issue by anshulchaurasia** [DataDog/zstd#81]
I am using 
go version go1.12.14 windows/amd64

I was trying to decompress using the streaming api and getting the error:

**zr := zstd.NewReader(bytes.NewBuffer(cbuf))
	buf, err = ioutil.ReadAll(zr)
	if err != nil {
		return nil, err
	}
	err = zr.Close()
	return**

**failed to decompress: Unknown frame descriptor** 

Reason behind that the service I am using to download data is adding some byte to make the block of fixed size.
Without padding it is working fine.
sample padding code:
	**n := len(itemList[i].comp) % 16
	   if n > 0 {
	                n = 16 - n
	                for ; n > 0; n-- {
                                    itemList[i].comp = append(itemList[i].comp, padding[0])
                                   }
                         }**

I was expecting it will be able to ignore the extra bytes but that is not the case.
Can you please help me how to resolve this.

**Comment by anshulchaurasia** [comment]
@Viq111 I hope you can help with this

**Comment by Viq111** [comment]
Hi @anshulchaurasia 

It looks like you are not consuming after doing a `zr.Close()`. When you close it actually flush the frame finish so you need to consume the rest via reading remaining data from`zr`.

It looks like it would be a common pitfall so I'll add to the documentation the exact code snippet

**Comment by anshulchaurasia** [comment]
hi @Viq111 

Could you please post the snippet here it will be very helpful.
As I am getting the error on the following line:

**buf, err = ioutil.ReadAll(zr)**

it's before calling Close().

**Comment by Viq111** [comment]
Oh sorry, I read it incorrectly and though you were compressing and not decompressing.
For decompression, zstd will try to interpret your padding as compressed data and will fail. You have to provide to the reader exactly the compressed data.

In your case (unrelated to zstd), you would probably want to prefix the data block by how much padding you are adding.

Something like: https://play.golang.org/p/7muxEHDJDTl

**Comment by anshulchaurasia** [comment]
Hi @Viq111 
As a consumer I am not aware how much padding is added so not able to remove it.
According to your previous comment I have to provide exactly the compressed data whereas decompression is working fine with padding upto 4 bytes.(verified with a sample code)
Can you please explain how it is working and is there any possible way to work with any numbers of padded bytes?

Thanks

**Comment by anshulchaurasia** [comment]
Hi @Viq111 

Any suggestion from your side?

Thanks

**Comment by Viq111** [comment]
I haven't looked too much at the internals of the compression algorithm of zstd unfortunately ( https://github.com/facebook/zstd/issues would probably be a better place to ask about it) so I'm not sure about the guarantee of the end of frame (i.e: can a frame finish with zero bytes).
It's usually pretty common for systems adding padding to provide the size of it because you cannot know if the extra pad is real data or not
