### ISSUE TITLE
Support zstd dictionary API for non-streaming use

### ISSUE THREAD

**Issue by chrbsg** [DataDog/zstd#85]
The following zstd functions are not currently wrapped or exposed:

- Simple dictionary API
  - ZSTD_compress_usingDict
  - ZSTD_decompress_usingDict

- Bulk processing dictionary API
  - ZSTD_createCDict
  - ZSTD_compress_usingCDict
  - ZSTD_createDDict
  - ZSTD_decompress_usingDDict

**Comment by heikkisalokantosc** [comment]
Any progress on this?

Dictionaries are very effective in small JSON compression, which is a pretty common use-case nowadays.

**Comment by Viq111** [comment]
Hi @heikkisalokantosc,

If you want to use dictionaries that you already generated (via the [zstd cli dictionary builder](https://github.com/facebook/zstd/tree/dev/programs#command-line-interface-for-zstandard-library) for example), you can use [`NewWriterLevelDict`](https://pkg.go.dev/github.com/DataDog/zstd?utm_source=godoc#NewWriterLevelDict) (Compression) and [`zstd.NewReaderDict`](https://pkg.go.dev/github.com/DataDog/zstd?utm_source=godoc#NewReaderDict) (Decompression)

The bulk processing dictionary API was added in https://github.com/DataDog/zstd/pull/114

Do you need the `Simple dictionary API` or would the stream dictionary API suit your need ?

**Comment by heikkisalokantosc** [comment]
Thanks @Viq111, I've just missed the bulk processor completely. It's exactly what I need for processing thousands of small JSONs.

**Comment by Viq111** [comment]
I'm going to close this one since the main use case (compressing/decompressing with a dictionary in a non-streaming fashion (i.e: to not recreate expensive objects)) has been implemented in https://github.com/DataDog/zstd/pull/114.

Feel free to open a separate issue if other use cases are not served well.
