### ISSUE TITLE
If I have two types data --compressed and uncompressed, when I call the DeCompress function, would it report an error?

### ISSUE THREAD

**Issue by RonCheen** [DataDog/zstd#88]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.14

### What operating system and processor architecture are you using (`go env`)?
mac os 10.15.6  Intel Core i7

### What did you do?

If possible, provide a recipe for reproducing the error.
If you have issues building, please parse the output of `go build -x`

I want to process two sources of data, one is compressed by zstd, but the other is not, at the end , they will both call the DeCompress function provided by you, will DeCompress function distinguish them？

### What did you expect to see?
When uncompressed data call DeCompress function, DeCompress function will do noting

**Comment by Viq111** [comment]
Hi @RonCheen 

The call to `Decompress` on non-valid data (in this case uncompressed) is undefined since zstd doesn't have a way to know if it's correct data or not. If the structure appears to be some zstd data it will try to process it and in other cases, it might return an error
