### ISSUE TITLE
Add Go module file

### ISSUE THREAD

**Issue by nezorflame** [DataDog/zstd#89]
In order for others to use the only currently supported vendor solution aka [Go modules](https://blog.golang.org/using-go-modules), this project needs a `go.mod` file.

This would also help with confusion some people have over the import name (`DataDog` vs `datadog`) - since the module file will contain the package name, it'll be the only proper import path after the module file gets merged.

Which one it should have is probably up for discussion (or as the author decides).

**Comment by nezorflame** [comment]
@Viq111 thanks!

**Comment by Viq111** [comment]
Sorry for the delay!
We were looking at https://github.com/DataDog/zstd/pull/91 which is a release blocker.
As soon as it's merged (hopefully soon, just need to be able to consistently reproduce in CI tests), I'll cut a new release. I would recommend waiting for that PR to be merged first
