### ISSUE TITLE
Error while decompression

### ISSUE THREAD

**Issue by prabhat003** [DataDog/zstd#9]
I am facing the following issue. Its during decompression
For compression the 'Data' that i am pushing is json data from an api. Compression is working perfectly.
Can some one help me with this.

Compression

var rs = new stream.Readable({ objectMode: true });
var chunks = [];
  rs.push(Data);
  rs.push(null);
  rs.pipe()
    .pipe(compressStream())
    .on('data', function(chunk) {
    chunks.push(chunk);
     })
    .on('end',function(){ 
     Buffer.concat(chunks);
    });

Decompression

var ds = new stream.Readable();
    ds.push(chunks.toString());
    ds.push(null);
    ds.pipe(decompressStream())
        .pipe(process.stdout);

Error

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Unknown frame descriptor
    at Error (native)

**Comment by Viq111** [comment]
Hi,
this is the Go binding for zstd. It seems like you are using JS so I'd advice to try to get help from the author of your library (alternatively you could try to find the best binding for your languages on the official zstd homepage here: http://facebook.github.io/zstd/)

Closing for now
